# -*- coding: utf-8 -*-
"""Akramov

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRC11BEn1c75qsVMAq8Xpw16nt-pVnqn
"""

import pandas as pd
df = pd.read_excel("titanik.xlsx")
print(data.head())

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
filtr = df[df['Age'] <15]
print(filtr)

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
filtr = df[df['Age'] >15]
print(filtr)